apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-demo
  namespace: kafka-demo
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true        
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.5"
      auto.create.topics.enable: false
      delete.topic.enable: true
      group.initial.rebalance.delay.ms: 3000
      num.partitions: 4
    storage:
      type: jbod
      volumes:
        - id: 0
          class: directpv-min-io
          type: persistent-claim
          size: 1Gi
          deleteClaim: false
  zookeeper:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storage:
      class: directpv-min-io
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}


