# loosely based on https://blog.devgenius.io/automating-installation-of-ha-rke2-kubernetes-cluster-with-ansible-2456cc95d970

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      recurse: yes
    loop:
      - /etc/rancher/rke2
      - /var/lib/rancher/rke2/server/manifests

  - name: get hostname short
    shell: |
      hostname -s
    register: hostname_short
    changed_when: False

  - name: hostname fqdn
    shell: |
      hostname -f
    register: hostname_fqdn
    changed_when: False

  - name: Print hostname fqdn and short
    debug:
      msg:
      - "hostname short '{{ hostname_short.stdout }}'"
      - "hostname fqdn: '{{ hostname_fqdn.stdout }}'"

  - name: Creating the config.yaml
    copy:
      dest: "{{ CONFIG_FILE }}"
      content: |
        tls-san:
          - "{{ hostname_short.stdout }}"
          - "{{ hostname_fqdn.stdout }}"
          - "{{ hosts_gw }}"
          - "{{ ext_dns_name }}"
        cni: "cilium"
        {% if controller_worker is not defined %}
        node-taint:
          - "CriticalAddonsOnly=true:NoExecute"
        {% endif %}
    notify: "rke2-server service restart"

  - name: Creating the CoreDNS config file
    copy:
      dest: "/var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml"
      content: |
        apiVersion: helm.cattle.io/v1
        kind: HelmChartConfig
        metadata:
          creationTimestamp: null
          name: rke2-coredns
          namespace: kube-system
        spec:
          valuesContent: |-
            nodelocal:
              enabled: true # Change this to false or remove this (Creating the CoreDNS config file) section altogether if you don’t want to install NodeLocal DNSCache
          bootstrap: true
    notify: "rke2-server service restart"

  - name: download rke2.sh
    get_url:
      url: https://get.rke2.io
      dest: /root/rke2.sh
      mode: '0700'

  - name: Installing rke2 server
    command: /root/rke2.sh
    environment: 
      INSTALL_RKE2_VERSION: "{{ rke2_version|default('') }}"

  - name: Starting rke2 server
    systemd:
      name: rke2-server
      state: restarted
      enabled: true

  - name: kubeconfig directory
    file:
      path: /root/.kube
      state: directory
      mode: '0700'

  - name: kubeconfig link
    file:
      dest: /root/.kube/config
      src: /etc/rancher/rke2/rke2.yaml 
      state: link

  - name: kubectl binary
    file:
      dest: /usr/local/bin/kubectl
      src: /var/lib/rancher/rke2/bin/kubectl
      state: link

