---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Uninstall DirectPV
  vars:
    K: "{{ playbook_dir }}/.kubeconfig"

  tasks:
    - name: List cluster components
      command: hostname
      changed_when: none

    - name: Uninstall DirectPV
      pause:
        prompt: Are you sure? Press return to continue. Press Ctrl+c and then "a" to abort

    - name: Check PVC with directpv-min-io storage class
      shell:
        cmd: kubectl --kubeconfig=.kubeconfig get pvc -A 2>/dev/null | grep directpv-min-io | wc -l | sed -e 's/ //g'
      register: how_many_pvc

    - fail:
        msg: |
            Found {{ how_many_pvc.stdout }} PVC with directpv-min-io storage class
            You will need to manually delete them then re-run this playbook.
      when: how_many_pvc.stdout != "0"

    - name: Uninstall directpv
      shell: 
        cmd: kubectl-directpv uninstall --kubeconfig=.kubeconfig && rm .directpv.yaml .drives.yaml .drives.init
        removes: .directpv.yaml

    - name: Remove directpv local files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ./.drives.init
        - ./.drives.yaml
        - ./.directpv.yaml

- hosts: worker
  gather_facts: false
  name: Cleanup directpv on workers
  
  tasks:

# ansible mount module requires path which sucks
    - name: Umount device
      shell: umount "/dev/{{ directpv_device }}"
      failed_when: none 

    - name: wipefs
      shell: wipefs -a "/dev/{{ directpv_device }}"
     
