---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Install CNPG - Cloud Native Postgres

  tasks:
    - kubernetes.core.helm_repository:
        name: cnpg
        repo_url: https://cloudnative-pg.github.io/charts

    - kubernetes.core.helm:
        name: cnpg
        namespace: cnpg-system
        chart_ref: cnpg/cloudnative-pg
        chart_version: "{{ cnpg_chart_version|default('') }}"
        create_namespace: yes

