---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Install dummy
  vars:
    D: "/root/.kubesol"

  tasks:
    - name: dummy template j2 -> yaml
      template:
        src: "files/dummy/{{ item }}.j2"
        dest: "{{ D }}/.{{ item }}.yaml"
      with_items:
        - dummy-ns
        - dummy-ing
        - dummy-issuer
        - dummy-svc
        - dummy-sts
        
    - name: dummy apply yamls
      kubernetes.core.k8s:
        state: present
        src: "{{ D }}/.{{ item }}.yaml"
      with_items:
        - dummy-ns
        - dummy-ing
        - dummy-issuer
        - dummy-svc
        - dummy-sts

