---
- hosts: localhost
  gather_facts: false
  connection: local
  name: loki helm uninstall
  vars:

  tasks:
    - name: Remove loki
      kubernetes.core.helm:
        name: loki
        namespace: monitoring
        state: absent
        wait: true

    - name: Remove Promtail
      kubernetes.core.helm:
        name: promtail
        namespace: monitoring
        state: absent
        wait: true

