---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Add Trivy Grafana dashboard

  tasks:
    - name: Add Trivy Grafana Dashboard
      kubernetes.core.k8s:
        state: present
        src: files/trivy/grafana-dashboard.yaml