---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Install strimzi kafka operator
  vars:
    NS: "strimzi"

  tasks:
    - include_tasks: tasks/namespace.yaml

    - kubernetes.core.helm:
        name: strimzi
        chart_ref: "oci://quay.io/strimzi-helm/strimzi-kafka-operator"
        chart_version: "{{ strimzi_chart_version|default('') }}"
        release_namespace: "{{ NS }}"
        values:
          watchAnyNamespace: true