---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Install Vault
  vars:
    K: "{{ playbook_dir }}/.kubeconfig"

  tasks:
    - kubernetes.core.helm_repository:
        name: hashicorp
        repo_url:  https://helm.releases.hashicorp.com

    - name: create namespace vault
      kubernetes.core.k8s:
        name: vault
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ K }}"

    - name: vault issuer
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ K }}"
        definition:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: letsencrypt-vault
            namespace: vault
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: "{{ letsencrypt_email }}"
              privateKeySecretRef:
                name: letsencrypt-vault
              solvers:
                - http01:
                    ingress:
                      ingressClassName: nginx
          
    - name: vault install helm chart
      kubernetes.core.helm:
        name: vault
        release_namespace: vault
        chart_ref: hashicorp/vault
        chart_version: "{{ vault_chart_version|default('') }}"
        kubeconfig: "{{ K }}"
        values:
          global:
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 256Mi

          ui:
            enabled: true 

          injector:
            enabled: false
          
          server:
            ingress:
              enabled: true
              ingressClassName: "nginx"
              annotations: 
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
                cert-manager.io/issuer: "letsencrypt-vault"
              hosts:
                - host: "vault.{{ ext_dns_name }}"
                  paths: []
              tls:
                - secretName: vault-tls
                  hosts:
                    - "vault.{{ ext_dns_name }}"

            dataStorage:
              enabled: true
              size: 1Gi
              storageClass: longhorn
              
            ha:
              enabled: true
              replicas: 3
              raft:
                enabled: true
                config: |
                  ui = true
                  listener "tcp" {
                    tls_disable = 1
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                  }
                  storage "raft" {
                    path = "/vault/data"
                  }
                  service_registration "kubernetes" {}
          
          
