---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Install external-secrets
  vars:
    NS: "external-secrets"

  tasks:
    - name: external-secrets helm repo
      kubernetes.core.helm_repository:
        name: external-secrets
        repo_url: https://charts.external-secrets.io

    - include_tasks: tasks/namespace.yaml

    - name: external-secrets helm install
      kubernetes.core.helm:
        name: external-secrets
        chart_ref: external-secrets/external-secrets
        chart_version: "{{ external_secrets_chart_version|default('') }}"
        namespace: "{{ NS }}"
        values:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          
#eof
